target("Game 2 - Alpha - Circle shoots Cubes")
    add_files("Game 2 Alpha - Circle Shoots Cubes.cpp")
    set_kind("binary")
    add_qt()
    add_string_formatting()
    add_logging_support_for_binaries()
