target("Simp1e.exe")
    set_kind("binary")
    add_files("Simp1e.cpp", "Simp1e.rc")
    set_filename("Simp1e.exe")
    add_ldflags("/subsystem:windows")
    add_ldflags("/entry:WinMainCRTStartup", { force = true })
    add_deps("Gooey.wxWidgets")
    add_wx()

    after_build(function(target)
        os.cp("Resources/Images/Logo/Simp1e 256.png", path.join(target:targetdir(), "Logo.png"))
    end)
