target("Simp1e.Qt.ECS.DLL")
    set_kind_qt_shared_library()
    set_basename("Simp1e.Qt.ECS")
    add_logging_runtime()
    add_string_formatting()
    add_deps("Simp1e.ServiceHost", "Simp1e.ECS.Services", "Simp1e.Qt.ECS", "Simp1e.ECS.Components.Common")
    add_files("Simp1e.Qt.ECS.DLL.cpp")
