target("Prototype - Does Something in 3D")
    add_files("Prototype - Does Something in 3D.cpp")
    set_kind("binary")
    add_qt()
    add_3d_qt_libs()
    add_includedirs(".")
    add_string_formatting()
    add_logging_support_for_binaries()
    add_deps("Simp1e.UI", "Simp1e.Qt", "Simp1e.Maps", "Simp1e.UI.Maps", "Simp1e.Qt.Maps")
    add_defines("_CRT_SECURE_NO_WARNINGS")
