includes("xmake/*.lua")
add_rules("mode.debug", "mode.release")
set_languages("c++20")
add_requires("_Log_", "spdlog")
add_requires_for_specs()
add_requires_for_string_formatting()
includes("Simp1e*/xmake.lua")
