#pragma once

namespace Simp1e {
    enum class GamepadButton {
        None,
        JoyX,
        JoyY,
        JoyZ,
        JoyR,
        JoyU,
        JoyV,
        JoyPOV,
        JoyButtons,
        JoyButtons1,
        JoyButtons2,
        JoyButtons3,
        JoyButtons4,
        JoyButtons5,
        JoyButtons6,
        JoyButtons7,
        JoyButtons8,
        JoyButtons9,
        JoyButtons10,
        JoyButtons11,
        JoyButtons12,
        JoyButtons13,
        JoyButtons14,
        JoyButtons15,
        JoyButtons16,
        JoyButtons17,
        JoyButtons18,
        JoyButtons19,
        JoyButtons20,
        JoyButtons21,
        JoyButtons22,
        JoyButtons23,
        JoyButtons24,
        JoyButtons25,
        JoyButtons26,
        JoyButtons27,
        JoyButtons28,
        JoyButtons29,
        JoyButtons30,
        JoyButtons31,
        JoyButtons32
    };
}
