#pragma once

namespace Simp1e {
    enum class KeyboardKey : int {
        Unknown = -2,
        None    = -1,

        Key0 = 0,
        Key1 = 1,
        Key2 = 2,
        Key3 = 3,
        Key4 = 4,
        Key5 = 5,
        Key6 = 6,
        Key7 = 7,
        Key8 = 8,
        Key9 = 9,

        NumPad0       = 10,
        NumPad1       = 11,
        NumPad2       = 12,
        NumPad3       = 13,
        NumPad4       = 14,
        NumPad5       = 15,
        NumPad6       = 16,
        NumPad7       = 17,
        NumPad8       = 18,
        NumPad9       = 19,
        NumPadDecimal = 20,

        F1  = 21,
        F2  = 22,
        F3  = 23,
        F4  = 24,
        F5  = 25,
        F6  = 26,
        F7  = 27,
        F8  = 28,
        F9  = 29,
        F10 = 30,
        F11 = 31,
        F12 = 32,

        A = 33,
        B = 34,
        C = 35,
        D = 36,
        E = 37,
        F = 38,
        G = 39,
        H = 40,
        I = 41,
        J = 42,
        K = 43,
        L = 44,
        M = 45,
        N = 46,
        O = 47,
        P = 48,
        Q = 49,
        R = 50,
        S = 51,
        T = 52,
        U = 53,
        V = 54,
        W = 55,
        X = 56,
        Y = 57,
        Z = 58,

        Backspace   = 59,
        Delete      = 60,
        Tab         = 61,
        Enter       = 62,
        Pause       = 63,
        CapsLock    = 64,
        Escape      = 65,
        Space       = 66,
        PageUp      = 67,
        PageDown    = 68,
        End         = 69,
        Home        = 70,
        PrintScreen = 71,
        Insert      = 72,

        Up    = 73,
        Down  = 74,
        Left  = 75,
        Right = 76,

        NumPadMultiply = 77,
        NumPadAdd      = 78,
        NumPadSubtract = 79,
        NumPadDivide   = 80,

        NumLock    = 81,
        ScrollLock = 82,

        LeftShift  = 83,
        RightShift = 84,
        LeftCtrl   = 85,
        RightCtrl  = 86,
        LeftAlt    = 87,
        RightAlt   = 88,

        Semicolon    = 89,
        Plus         = 90,
        Comma        = 91,
        Minus        = 92,
        Period       = 93,
        Slash        = 94,
        Tilde        = 95,
        LeftBracket  = 96,
        Backslash    = 97,
        RightBracket = 98,
        Quote        = 99,

        LeftSuper  = 100,
        RightSuper = 101,

        Menu = 102
    };
}
