target("Prototype - Resize Map Elements")
    add_files("Prototype - Resize Map Elements.cpp")
    set_kind("binary")
    add_qt()
    add_includedirs(".")
    add_string_formatting()
    add_logging_support_for_binaries()
    add_deps("Simp1e.UI", "Simp1e.Qt.v1", "Simp1e.Maps", "Simp1e.UI.Maps", "Simp1e.Qt.Maps")
    add_defines("_CRT_SECURE_NO_WARNINGS")
