target("Game - Simpler Side Scroller")
    add_files("Game - Simpler Side Scroller.cpp")
    set_kind("binary")
    add_qt()
    add_includedirs(".", "include")
    add_string_formatting()
    add_logging_support_for_binaries()
    add_packages("nlohmann_json")
    add_deps("Simp1e", "Simp1e.UI", "Simp1e.Qt", "Simp1e.ECS", "Simp1e.ECS.Components")
    add_defines("_CRT_SECURE_NO_WARNINGS")
