target("Prototype - Map Tile Images")
    add_files("Prototype - Map Tile Images.cpp")
    set_kind("binary")
    add_qt()
    add_includedirs(".")
    add_string_formatting()
    add_logging_support_for_binaries()
    add_deps("Prototyping Shared Library")
    add_defines("_CRT_SECURE_NO_WARNINGS")
