target("Simp1e.ECS.Services")
    set_kind("headeronly")
    add_includedirs("include", {public = true})
    add_headerfiles("include/(**.h)")
    add_deps("Simp1e.ECS.Core", "Simp1e.ECS.PointerStorage", "Simp1e.ECS.PointerStorageClient")
